services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  redis:
    image: redis:latest
    container_name: optimized-deleting-in-redis-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    logging:
      driver: none
    
  redis-exporter:
    image: oliver006/redis_exporter:v1.6.0-alpine
    ports:
      - 9121:9121
    depends_on:
      - redis
    command:
      - '--redis.addr=redis://redis:6379'
  
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   container_name: optimized-deleting-in-redis-app
  #   depends_on:
  #     - redis
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #   volumes:
  #     - ./:/src
  #     - $GOPATH/pkg/mod:/go/pkg/mod
  #   working_dir: /src
  #   command: air -c .air.toml
